version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bebrivus_db
      - POSTGRES_USER=bebrivus_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8001 --workers 4
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    restart: always

  daphne:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8002 core.asgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
