# Generated by Django 4.2.16 on 2026-02-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Session Booking'), ('cancellation', 'Session Cancellation'), ('reminder', 'Session Reminder'), ('admin_escalation', 'Admin Escalation'), ('institution_activity', 'Institution Activity')], max_length=30),
        ),
    ]
