# Generated by Django 4.2.16 on 2026-02-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Session Booking'), ('cancellation', 'Session Cancellation'), ('reminder', 'Session Reminder'), ('admin_escalation', 'Admin Escalation'), ('institution_activity', 'Institution Activity'), ('moderation', 'Content Moderation'), ('ai_coach', 'AI Coach Alert'), ('user_registration', 'User Registration'), ('application', 'Application Submitted')], max_length=30),
        ),
    ]
