# Generated by Django 4.2.16 on 2026-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_e2e_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2emessage',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='e2emessage',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
