# Generated by Django 4.2.16 on 2026-03-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_add_is_encrypted_to_e2emessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2emessage',
            name='sender_encrypted_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='e2emessage',
            name='sender_nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='e2emessage',
            name='sender_public_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
