# Generated by Django 4.2.16 on 2026-03-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_sender_copy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2emessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='e2emessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
