# Generated by Django 4.2.16 on 2026-03-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('general', 'General Feedback'), ('other', 'Other'), ('student_quality', 'Student Application Quality'), ('platform_posting', 'Opportunity Posting Issue'), ('application_process', 'Application Process Problem'), ('student_conduct', 'Student Conduct Report'), ('partnership', 'Partnership Inquiry'), ('platform_bug', 'Platform Bug'), ('billing_admin', 'Billing / Admin Issue'), ('session_issue', 'Session / Booking Problem'), ('student_behaviour', 'Student Behaviour Report'), ('payment_payout', 'Payment / Payout Issue'), ('profile_visibility', 'Profile or Visibility Issue'), ('scheduling', 'Scheduling Problem'), ('communication', 'Communication Issue'), ('feature_request', 'Feature Request')], default='general', max_length=30),
        ),
    ]
