# Generated by Django 6.0.2 on 2026-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('community_talent_professional', 'Community Talent Professional'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('institution', 'Institution')], default='student', max_length=40),
        ),
    ]
