# Generated by Django 4.2.16 on 2026-03-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_registration', 'User Registration'), ('application', 'Application'), ('opportunity', 'Opportunity'), ('booking', 'Booking')], max_length=50)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='activity', max_length=50)),
                ('user', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
