# Generated by Django 4.2.16 on 2026-03-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_change_submitted_to_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('clicked', 'Clicked'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
