# Generated by Django 4.2.16 on 2026-02-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('skills_mentioned', models.JSONField(default=list)),
                ('career_goals', models.TextField(blank=True)),
                ('interests', models.JSONField(default=list)),
                ('past_topics', models.JSONField(default=list)),
                ('last_conversation_summary', models.TextField(blank=True)),
                ('conversation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_memory_profiles',
            },
        ),
        migrations.CreateModel(
            name='ContentModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('forum_post', 'Forum Post'), ('chat_message', 'Chat Message'), ('application', 'Application'), ('profile', 'User Profile')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('content_text', models.TextField()),
                ('violation_category', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('removed', 'Removed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_moderation_flags',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='content_mod_status_46619e_idx'), models.Index(fields=['flagged_user'], name='content_mod_flagged_37d24c_idx')],
            },
        ),
    ]
