# Generated by Django 4.2.16 on 2026-02-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_usermemoryprofile_contentmoderationflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-is_starred', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
