# Generated by Django 4.2.16 on 2026-02-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='ai_moderation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_flagged', 'Auto Flagged by AI')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='reply',
            name='ai_moderation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reply',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_flagged', 'Auto Flagged by AI')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='forummoderationlog',
            name='action',
            field=models.CharField(choices=[('pin', 'Pin Discussion'), ('unpin', 'Unpin Discussion'), ('lock', 'Lock Discussion'), ('unlock', 'Unlock Discussion'), ('delete', 'Delete Content'), ('edit', 'Edit Content'), ('mark_solution', 'Mark as Solution'), ('unmark_solution', 'Unmark as Solution'), ('ai_flag', 'AI Flagged Content'), ('approve', 'Approve Content'), ('reject', 'Reject Content')], max_length=20),
        ),
    ]
