# Generated by Django 4.2.16 on 2026-02-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_discussion_ai_moderation_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('content', models.TextField()),
                ('author_username', models.CharField(max_length=255)),
                ('violation_categories', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_flagged_content',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warn', 'Warn User'), ('remove', 'Remove Content'), ('suspend', 'Suspend Account'), ('dismiss', 'Dismiss Flag')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flagged_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='forum.flaggedcontent')),
            ],
            options={
                'db_table': 'forum_moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
