# Generated by Django 4.2.16 on 2026-03-02 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_flaggedcontent_moderationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/images/'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='forum.discussion'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='repost_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReplyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='inappropriate', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.reply')),
            ],
            options={
                'unique_together': {('reply', 'flagged_by')},
            },
        ),
        migrations.CreateModel(
            name='DiscussionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('clap', 'Clap'), ('insightful', 'Insightful'), ('laugh', 'Laugh'), ('idea', 'Idea')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discussion', 'user')},
            },
        ),
    ]
