# Generated by Django 4.2.16 on 2026-03-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_discussion_image_discussion_is_repost_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyflag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replyflag',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='replyflag',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='is_repost',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='repost_count',
        ),
        migrations.DeleteModel(
            name='DiscussionReaction',
        ),
        migrations.DeleteModel(
            name='ReplyFlag',
        ),
    ]
