# Generated by Django 4.2.16 on 2026-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_replyflag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum/images/'),
        ),
    ]
