# Generated by Django 4.2.16 on 2026-03-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_discussion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReplyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('inappropriate', 'Inappropriate Content'), ('violence', 'Violence or Threats'), ('other', 'Other')], default='inappropriate', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.reply')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reply_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_reply_flags',
                'unique_together': {('reply', 'flagged_by')},
            },
        ),
        migrations.CreateModel(
            name='DiscussionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('inappropriate', 'Inappropriate Content'), ('violence', 'Violence or Threats'), ('other', 'Other')], default='inappropriate', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='forum.discussion')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discussion_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_discussion_flags',
                'unique_together': {('discussion', 'flagged_by')},
            },
        ),
    ]
