# Generated by Django 4.2.16 on 2026-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_type',
            field=models.CharField(choices=[('internal', 'Internal Application'), ('external', 'External Application')], default='internal', max_length=20),
        ),
    ]
