# Generated by Django 4.2.16 on 2026-03-02 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0002_opportunity_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='posted_by_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('institution', 'Institution')], default='admin', max_length=20),
        ),
    ]
