# Generated by Django 4.2.16 on 2026-02-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_mentorprofile_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
