# Generated by Django 4.2.16 on 2026-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_alter_mentorshipsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipsession',
            name='session_type',
            field=models.CharField(choices=[('career_guidance', 'Career Guidance'), ('interview_prep', 'Interview Preparation'), ('skill_development', 'Skill Development'), ('portfolio_review', 'Portfolio Review'), ('networking', 'Networking'), ('general', 'General Mentoring'), ('video', 'Video Call'), ('chat', 'Text Chat'), ('email', 'Email'), ('in_person', 'In Person'), ('other', 'Other')], max_length=20),
        ),
    ]
